# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-27 23:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewAnnouncement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement_title', models.CharField(max_length=60)),
                ('announcement_type', models.CharField(choices=[('danger', 'Critical'), ('info', 'Information'), ('warning', 'Warning')], max_length=7)),
                ('announcement_description', models.TextField()),
                ('announcement_date', models.DateTimeField(auto_now=True)),
                ('announcement_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UpdateHomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_section', models.TextField()),
                ('facilities_section', models.TextField()),
                ('general_section', models.TextField()),
            ],
        ),
    ]
