# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-28 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_updatersocalendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatersocalendar',
            name='rso_title',
            field=models.CharField(default='RSO Duity', max_length=20),
        ),
    ]
