# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-28 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_updatersocalendar_rso_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatersocalendar',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='updatersocalendar',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
